"""Initial schema.

Revision ID: 0001_initial
Revises:
Create Date: 2026-07-02
"""

from alembic import op
import sqlalchemy as sa

revision = "0001_initial"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # The first implementation can bootstrap with SQLAlchemy metadata during local dev.
    # Production deployments should replace this placeholder with an autogenerated migration
    # after dependency installation.
    pass


def downgrade() -> None:
    pass

